   package mars;
	
   import mars.venus.*;
   import mars.assembler.*;
   import mars.simulator.*;
   import mars.mips.hardware.*;

   import java.net.URISyntaxException;
   import java.nio.charset.*;
   import java.nio.file.Files;
   import java.nio.file.Path;
   import java.nio.file.Paths;
   import java.util.*;
   import java.io.*;
   import java.awt.event.*;
   import javax.swing.*;

/*
Copyright (c) 2003-2006,  Pete Sanderson and Kenneth Vollmar

Developed by Pete Sanderson (psanderson@otterbein.edu)
and Kenneth Vollmar (kenvollmar@missouristate.edu)

Permission is hereby granted, free of charge, to any person obtaining 
a copy of this software and associated documentation files (the 
"Software"), to deal in the Software without restriction, including 
without limitation the rights to use, copy, modify, merge, publish, 
distribute, sublicense, and/or sell copies of the Software, and to 
permit persons to whom the Software is furnished to do so, subject 
to the following conditions:

The above copyright notice and this permission notice shall be 
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, 
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. 
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR 
ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF 
CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

(MIT license, http://www.opensource.org/licenses/mit-license.html)
 */

/**
 * Internal representations of MIPS program.  Connects source, tokens and machine code.  Having
 * all these structures available facilitates construction of good messages,
 * debugging, and easy simulation.
 * 
 * @author Pete Sanderson
 * @version August 2003
 **/

    public class MIPSprogram {
      private Path source;
      final private List<TokenList> tokenList = new ArrayList<>();
      private List<ProgramStatement> parsedList;
      private ArrayList machineList;
      private SymbolTable localSymbolTable;
      private MacroPool macroPool;
      final private List<SourceLine> sourceLineList = new ArrayList<>();
		private Tokenizer tokenizer;
   
   /**
    * Set list of source statements that comprise the program.
    * @param sourceLineList ArrayList of SourceLine.  
	 * Each SourceLine represents one line of MIPS source code.
    **/
   	
       public void setSourceLineList(ArrayList<SourceLine> sourceLineList) {
         this.sourceLineList.clear();
         this.sourceLineList.addAll(sourceLineList);
      }
   
   /**
    * Retrieve list of source statements that comprise the program.
    * @return ArrayList of SourceLine.  
	 * Each SourceLine represents one line of MIPS source cod
    **/
   	
       public List<SourceLine> getSourceLineList() {
         return this.sourceLineList;
      }
   
   /**
    * Produces name of associated source code file.
    * @return File name as String. 
    **/
    
       public String getFilename() {
         return source.toString();
      }
   
   /**
    * Produces list of tokens that comprise the program.
    * @return ArrayList of TokenList.  Each TokenList is list of tokens generated by
    * corresponding line of MIPS source code.
    * @see TokenList
    **/
    
       public List<TokenList> getTokenList() {
         return tokenList;
      }
   
   /**
    * Retrieves Tokenizer for this program
    * @return Tokenizer
    **/   
    
       public Tokenizer getTokenizer() {
         return tokenizer;
      }	
		
   /**
    * Produces new empty list to hold parsed source code statements.
    * @return ArrayList of ProgramStatement.  Each ProgramStatement represents a parsed
    * MIPS statement.
    * @see ProgramStatement
    **/
    
       public List<ProgramStatement> createParsedList() {
         parsedList = new ArrayList<>();
         return parsedList;
      }
   
   /**
    * Produces existing list of parsed source code statements.
    * @return ArrayList of ProgramStatement.  Each ProgramStatement represents a parsed
    * MIPS statement.
    * @see ProgramStatement
    **/
    
       public List<ProgramStatement> getParsedList() {
         return parsedList;
      }
   
   /**
    * Produces list of machine statements that are assembled from the program.
    * @return ArrayList of ProgramStatement.  Each ProgramStatement represents an assembled
    * basic MIPS instruction.
    * @see ProgramStatement
    **/
    
       public ArrayList getMachineList() {
         return machineList;
      }

   /**
    * Returns SymbolTable associated with this program.  It is created at assembly time,
    * and stores local labels (those not declared using .globl directive).
    **/
    
       public SymbolTable getLocalSymbolTable() {
         return localSymbolTable;
      }
   
   /**
    * Produces specified line of MIPS source program.
    * @param i Line number of MIPS source program to get.  Line 1 is first line.
    * @return Returns specified line of MIPS source.  If outside the line range,
    * it returns null.  Line 1 is first line.
    **/
    
       public String getSourceLine(int i) {
         if ( (i >= 1) && (i <= sourceLineList.size()) )
            return sourceLineList.get(i-1).getSource();
         else
            return null;
      }


    /**
     * Reads MIPS source code from file into structure.  Will always read from file.
     * It is GUI responsibility to assure that source edits are written to file
     * when user selects compile or run/step options.
     *
     * @param path Path containing name of MIPS source code file.
     * @throws ProcessingException Will throw exception if there is any problem reading the file.
     **/
    public void readSource(Path path) throws ProcessingException {
        try {
            source = path;

            int lineNumber = 0;
            for (String line : Files.readAllLines(path)) {
                sourceLineList.add(new SourceLine(line, this, ++lineNumber));
            }
            
        } catch (Exception e) {
            ErrorList errors = new ErrorList();
            errors.add(new ErrorMessage((MIPSprogram) null, 0, 0, e.toString()));
            throw new ProcessingException(errors);
        }
    }

    /**
     * Tokenizes the MIPS source program. Program must have already been read from file.
     **/
    public void tokenize() {
        this.tokenizer = new Tokenizer();
        this.tokenList.clear();
        this.tokenList.addAll(tokenizer.tokenize(sourceLineList));
        this.localSymbolTable = new SymbolTable(getFilename()); // prepare for assembly
    }
   
   /**
    * Prepares the given list of files for assembly.  This involves
    * reading and tokenizing all the source files.  There may be only one.
    * @param filenames  ArrayList containing the source file name(s) in no particular order
    * @param leadFilename String containing name of source file that needs to go first and 
    * will be represented by "this" MIPSprogram object.
    * @param exceptionHandler String containing name of source file containing exception
    * handler.  This will be assembled first, even ahead of leadFilename, to allow it to
    * include "startup" instructions loaded beginning at 0x00400000.  Specify null or
    * empty String to indicate there is no such designated exception handler.
    * @return ArrayList containing one MIPSprogram object for each file to assemble.
    * objects for any additional files (send ArrayList to assembler)
    * @throws ProcessingException Will throw exception if errors occured while reading or tokenizing.
    **/
   
       public ArrayList prepareFilesForAssembly(List<String> filenames, String leadFilename, String exceptionHandler) throws ProcessingException {
           try {
               List<Path> paths = new ArrayList<>();

               Path lead = Paths.get(leadFilename).toRealPath();
               
               for (String filename: filenames) {
                   paths.add(Paths.get(filename).toRealPath());
               }
               paths.remove(lead);
               paths.add(lead);
               
               if (exceptionHandler != null && exceptionHandler.length() > 0) {
                   paths.add(0, Paths.get(exceptionHandler).toRealPath());
               } else {
                   paths.add(0, Paths.get(getClass().getResource("/kernel.s").toURI()).toRealPath());
               }
               
               return new ArrayList<>(process(paths));
           } catch (IOException | URISyntaxException e) {
               ErrorList errors = new ErrorList();
               errors.add(new ErrorMessage((MIPSprogram) null, 0, 0, e.toString()));
               throw new ProcessingException(errors);
           }
      }

      private static class Preprocessing {
           final int index;
           final int position;

          private Preprocessing(int index, int position) {
              this.index = index;
              this.position = position;
          }
      }
      
      private final List<Preprocessing> preprocessing = new ArrayList<>();
      
       private void preprocess() {
            // do not precess errors here!

           int index = -1;
           for (TokenList tokenizedLine : getTokenList()) {
               ++index;
               int position = 0;
               
               int size = tokenizedLine.size();
               if (size > 0 && tokenizedLine.get(size - 1).getType() == TokenTypes.COMMENT) {
                   --size;
               }

               // ignore optional label
               if (size >= 2) {
                   Token directive = tokenizedLine.get(position);
                   Token argument = tokenizedLine.get(position + 1);
                   if (argument.getType() == TokenTypes.COLON && directive.getType() == TokenTypes.IDENTIFIER) {
                       position = 2;
                   }
               }

               if (position >= size)
                   continue;

               Token directive = tokenizedLine.get(position);
               if (directive.getType() != TokenTypes.DIRECTIVE)
                   continue;


               TokenTypes argument = null;
               if (position + 1 < size)
                   argument = tokenizedLine.get(position + 1).getType();

               
               if (Directives.INCLUDE.matches(directive.getValue())) {
                   if (argument == TokenTypes.QUOTED_STRING) {
                       preprocessing.add(new Preprocessing(index, position));
                   }
                   continue;
               }

               if (Directives.EQV.matches(directive.getValue())) {
                   if (argument == TokenTypes.IDENTIFIER) {
                       preprocessing.add(new Preprocessing(index, position));
                   }
                   continue;
               }
           }
       }
       
    private static List<MIPSprogram> process(List<Path> initial) throws ProcessingException, IOException {
        Deque<Path> worklist = new ArrayDeque<>(initial);
        Map<Path, MIPSprogram> processed = new HashMap<>();

        while (!worklist.isEmpty()) {
            Path source = worklist.removeFirst().toRealPath();
            if (processed.containsKey(source))
                continue;

            MIPSprogram preparee = new MIPSprogram();
            preparee.source = source;
            preparee.readSource(source);
            preparee.tokenize();
            preparee.preprocess();

            processed.put(source, preparee);
            
            // find all dependent files / aka poor mens preprocessor#
            for (Preprocessing preprocess : preparee.preprocessing) {
                TokenList tokenList = preparee.tokenList.get(preprocess.index);
                Token directive = tokenList.get(preprocess.position);
                Token argument = tokenList.get(preprocess.position + 1);
                
                if (!Directives.INCLUDE.matches(directive.getValue()))
                    continue;
                
                // get rid of quotes
                String filename = argument.getValue();
                filename = filename.substring(1, filename.length() - 1);
                Path includePath = preparee.source.resolveSibling(Paths.get(filename));
                
                worklist.addFirst(includePath);
            }
        }


        List<MIPSprogram> result = new ArrayList<>();
        for (Path in : initial) {
            MIPSprogram unmodifed = processed.get(in.toRealPath());
            MIPSprogram modifed = new MIPSprogram();
            modifed.source = unmodifed.source;
            modifed.preprocessing.addAll(unmodifed.preprocessing);
            modifed.tokenList.addAll(unmodifed.tokenList);
            modifed.sourceLineList.addAll(unmodifed.sourceLineList);
            modifed.tokenizer = unmodifed.tokenizer;
            modifed.localSymbolTable = unmodifed.localSymbolTable;
            result.add(modifed);
        }

        
        // we cannot use RPO to precalculate anything, as loops in includes are valid and may only be stopped by macros
        // for that reason pre-processors are typically use an include depth limit!
        
        // process include / inlining
        for (MIPSprogram preparee : result) {
            // clang also uses this value, so it's more than enough
            final int maxAllowedIncludeStackDepth = 200;
            int depth = 0;

            boolean modified = true;
            while (modified) {
                modified = false;
                
                ++depth;
                if (depth >= maxAllowedIncludeStackDepth) {
                    ErrorList el = new ErrorList();
                    el.add(new ErrorMessage(preparee, 0,0, "Recursion Limit Reached"));
                    throw new ProcessingException(el);
                }
                
                int insertedLines = 0;
                ListIterator<Preprocessing> it = preparee.preprocessing.listIterator();
                while (it.hasNext()) {
                    Preprocessing preprocess = it.next();
                    final int realIndex = preprocess.index + insertedLines;

                    TokenList tokenList = preparee.tokenList.get(realIndex);
                    Token directive = tokenList.get(preprocess.position);
                    Token argument = tokenList.get(preprocess.position + 1);

                    if (Directives.INCLUDE.matches(directive.getValue())) {
                        modified = true;
                        it.remove();

                        // get rid of quotes
                        String filename = argument.getValue();
                        filename = filename.substring(1, filename.length() - 1);
                        Path includePath = preparee.source.resolveSibling(Paths.get(filename)).toRealPath();
                        MIPSprogram included = processed.get(includePath);

                        // remove directive, keep labels and errors for later handling
                        TokenList copy = (TokenList) tokenList.clone();
                        copy.remove(preprocess.position);
                        copy.remove(preprocess.position);
                        preparee.tokenList.set(realIndex, copy);
                        
                        // copy things, DO not touch sourceList!
                        preparee.tokenList.addAll(realIndex + 1, included.tokenList);

                        List<SourceLine> includeLines = included.sourceLineList;
                        preparee.sourceLineList.addAll(realIndex + 1, includeLines);

                        for (Preprocessing p : included.preprocessing) {
                            it.add(new Preprocessing(p.index + realIndex + 1, p.position));
                        }
                        
                        insertedLines += includeLines.size();
                        continue;
                    }

                    if (preprocess.index != realIndex) {
                        it.set(new Preprocessing(realIndex, preprocess.position));
                    }
                }
            }
        }

        return result;
    }
      

    /**
    * Assembles the MIPS source program. All files comprising the program must have 
    * already been tokenized.  Assembler warnings are not considered errors.
    * @param MIPSprogramsToAssemble ArrayList of MIPSprogram objects, each representing a tokenized source file.
    * @param extendedAssemblerEnabled A boolean value - true means extended (pseudo) instructions
    * are permitted in source code and false means they are to be flagged as errors.
    * @throws ProcessingException Will throw exception if errors occured while assembling.
    * @return ErrorList containing nothing or only warnings (otherwise would have thrown exception).
    **/
   
       public ErrorList assemble(ArrayList MIPSprogramsToAssemble, boolean extendedAssemblerEnabled)
              throws ProcessingException {   
         return assemble(MIPSprogramsToAssemble, extendedAssemblerEnabled, false);
      }
   	  
   /**
    * Assembles the MIPS source program. All files comprising the program must have 
    * already been tokenized.
    * @param MIPSprogramsToAssemble ArrayList of MIPSprogram objects, each representing a tokenized source file.
    * @param extendedAssemblerEnabled A boolean value - true means extended (pseudo) instructions
    * are permitted in source code and false means they are to be flagged as errors
    * @param warningsAreErrors A boolean value - true means assembler warnings will be considered errors and terminate
      the assemble; false means the assembler will produce warning message but otherwise ignore warnings.
    * @throws ProcessingException Will throw exception if errors occured while assembling.
    * @return ErrorList containing nothing or only warnings (otherwise would have thrown exception).
    **/
    
       public ErrorList assemble(ArrayList MIPSprogramsToAssemble, boolean extendedAssemblerEnabled,
              boolean warningsAreErrors) throws ProcessingException {
         Assembler asm = new Assembler();
         this.machineList = asm.assemble(MIPSprogramsToAssemble, extendedAssemblerEnabled, warningsAreErrors);
         return asm.getErrorList();
      }


    /**
    * Instantiates a new {@link MacroPool} and sends reference of this
    * {@link MIPSprogram} to it
    * 
    * @return instatiated MacroPool
    * @author M.H.Sekhavat {@literal <sekhavat17@gmail.com>}
    */
       public MacroPool createMacroPool() {
         macroPool = new MacroPool(this);
         return macroPool;
      }
   
   /**
    * Gets local macro pool {@link MacroPool} for this program
    * @return MacroPool
    * @author M.H.Sekhavat {@literal <sekhavat17@gmail.com>}
    */	
       public MacroPool getLocalMacroPool() {
         return macroPool;
      }
   
   /**
    * Sets local macro pool {@link MacroPool} for this program
    * @param macroPool reference to MacroPool
    * @author M.H.Sekhavat {@literal <sekhavat17@gmail.com>}
    */   
       public void setLocalMacroPool(MacroPool macroPool) {
         this.macroPool = macroPool;
      }
    
   }  // MIPSprogram
